version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend/web:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
